### ISSUE TITLE
Uncertain copy: "Paste an HTML5 link"

### ISSUE THREAD

**Issue by cemckinley** [mozilla/popcorn.webmaker.org#394]
Hi there, I'm not sure of what is meant by an "HTML5 link" in the placeholder text field copy "Paste an HTML5, YouTube, Vimeo, or SoundCloud link here" for adding media to a project. Does this mean a video file source from a video tag? Or the whole tag itself? It seems like there could be a more clear wording.

**Comment by thisandagain** [comment]
Resolved in https://github.com/mozilla/popcorn.webmaker.org/commit/48943337eb1f2b087fd23a4ca420c553ba6522e8#diff-3a2c4335e7c950b7a667b59c970a7f5eR145
