### ISSUE TITLE
Exported webmaker video on iOS/Android

### ISSUE THREAD

**Issue by STuFF** [mozilla/popcorn.webmaker.org#557]
Hi,

I didn't manage to replay webmaker's videos on iOS or Android devices (I used that one I did myself https://stuffk.makes.org/popcorn/25ef, it's just one imported youtube video)
Did I miss something or "mobile" support is not ready and planned for later ?

**Comment by thisandagain** [comment]
We don't have any plans to port popcorn.webmaker.org or popcorn.js to mobile browsers. Thanks for the question @STuFF !
