### ISSUE TITLE
Double scrollbars

### ISSUE THREAD

**Issue by scootergrisen** [mozilla/popcorn.webmaker.org#591]
Go to https://keyboardkat.makes.org/thimble/LTc4ODY2MDIyNA==/maker-party-event-reporter and notice how there might be two scrollbars.

Click "Details" to bring down the details and here there is also double scrollbars.

We can add one of these CSS codes to the iframes, depending on if we want the iframes to be block og inline to get rid of the double scrollbars:
```
vertical-align: bottom;
display: block;
```

**Comment by sanjaygouri** [comment]
Hello Scootergrisen I would like to work on this bug can i know more about this i mean where it has occurred ? .

**Comment by scootergrisen** [comment]
Just go to https://webmaker.org/en-US/explore and open one of the makes, it does not matter which one.

It also happens on Thimble when you open something that use the totorial frame on the left like here:
https://thimble.webmaker.org/da-DK/project/53812/remix

If you open that frame you can see the scrollbar which is not suppose to be there : https://mousemeredith.makes.org/thimble/NjM0NTE5NTUy/javascript-takeover-tutorial?details=hidden
