### ISSUE TITLE
Popcorn Makes Dissapeared 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/popcorn.webmaker.org#596]
Webmaker User: saramariacher
Lost: Two Popcorn Makes

Saved the makes at the beginning of February. 
Noticed they were lost one week later. 

Any ideas? 
@cadecairos @jbuck

**Comment by cadecairos** [comment]
I see two makes created by `saramariacher` in early February:
Feb 4: https://saramariacher.makes.org/popcorn/2oy6
Feb 3: https://saramariacher.makes.org/popcorn/2oss

**Comment by cadecairos** [comment]
https://webmaker.org/en-US/search?type=user&q=saramariacher

**Comment by LucyeoH** [comment]
I just sent those makes to the user to see if those are the makes that went missing.

**Comment by LucyeoH** [comment]
"The one from February 4th is one of the ones that he was missing, but the second one is a promotion from our instructor.  The subject of the one that is missing is Napoleon Dynamite remixed.  Either way, thank you for finding one of his videos!  He is very happy as well!" 

I have followed up to confirm the date of the second missing make.

**Comment by LucyeoH** [comment]
@cadecairos one of those was one of the missing ones. Apparently the other missing one was from the week before that. Anything on the Jan 26th, 27th, 28th?
