### ISSUE TITLE
"No Flash" message appears erroneously

### ISSUE THREAD

**Issue by gerv** [mozilla/popcorn.webmaker.org#606]
According to bmoskowitz, in recent Firefox, the No Flash message appears even though he has Flash installed. Perhaps Popcorn is checking at the wrong time? He said Firefox recently made some changes to late-load plugins, or something...

**Comment by Nolski** [comment]
I had the same issue but I think Firefox Developer Edition ships with an out of date version of flash as popcorn wasn't the only site throwing that error message and when I went and updated my version of flash, the error message went away.
