### ISSUE TITLE
Popcorn running fully on Heroku [saving make issue]

### ISSUE THREAD

**Issue by ianseyer** [mozilla/popcorn.webmaker.org#616]
Hi there!

Tagging @Pomax, for helping me earlier today.

I am attempting to get a popcorn instance fully functional on my own Heroku instance.

So far, I successfully have popcorn, login, and makeAPI instances running.

I am able to login via popcorn using either Persona or email login. However, I am unable to save makes. I get a generic "something went wrong" error, and my best guess is that Popcorn is not communicating with MakeAPI. However, I am not quite sure how to point Popcorn to Make. In the Popcorn config file, I have the MAKE_ENDPOINT set, however all of my makes are attempting:
`POST /en-US/api/project/ 500 19ms - 66b`

I am not quite sure where this route is coming from, or where it should be pointed at, and the documentation is difficult to get a complete picture from.

Is it relevant to the configuration's `AUDIENCE` parameter? I am unsure as to what this does as well.

Any guidance/further information needed?

**Comment by Pomax** [comment]
do you have the [MakeAPI](make-api running) already running?
